import fs from "fs";
import path from "path";

const ROOT = path.resolve(__dirname, "../src/assembler/grammar");
const JSON_PATH = path.join(ROOT, "z80_mnemonics.json");
const OUT_PATH = path.join(ROOT, "z80_mnemonics.peginc");

const mnemonics = JSON.parse(fs.readFileSync(JSON_PATH, "utf8"));

function makeRule(name: string, items: string[], kind: string): string {
  const pattern = items.map(s => `"${s}"i`).join(" / ");
  return `${name}\n  = $("${items.join('"i / "')}"i)\n    { return { kind: "${kind}", name: text().toUpperCase() }; }\n`;
}

const fileContent = `// Auto-generated by tools/gen-peggy-mnemonics.ts
// DO NOT EDIT MANUALLY
// Source: ${path.basename(JSON_PATH)}

${makeRule("RealInstr", mnemonics.instructions, "Instruction")}
${makeRule("PseudoInstr", mnemonics.directives, "Directive")}

Mnemonic
  = RealInstr / PseudoInstr
`;

fs.writeFileSync(OUT_PATH, fileContent);
console.log(`✅ Generated: ${OUT_PATH}`);
